# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Crónicas de un Birricidio"
description: > # this means to ignore newlines until "email:"
   "There is no such thing as a bad beer. </br>It's that some taste better than others" Billy Carter

email: birricida@outlook.com
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/Home.jpg"

name: 'Crónicas de un Birricidio'
author: 'El Birricida'
author_image: "/assets/images/logo.jpg"

paginate:	5

url: "http://birricida.github.io/" 
# the base hostname & protocol for your site
baseurl: "http://birricida.github.io/"
#used to display twitter cards
twitter_handle: '@birricida'

#fill in disqus shortname to use disqus
disqus: Birricida

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/birricida
    desc: Sigueme en twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="


#  - icon:	untappd
#    url:	https://
#    desc:	A
#    share_url:
#    share_title:
#    share_link:

  - icon:	beer
    url:	https://untappd.com/user/Birricida
    desc:	Sígueme en Untappd
    share_url:
    share_title:
    share_link: